language: julia

os:
  - linux

julia:
  - 1.0.3

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();Pkg.add("Documenter")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
