language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();'
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
