name: Docs
site_name:        CpelAsm.jl
repo_url:         https://github.com/JuliaDocs/CpelAsm.jl
site_description: Julia package for allele-specific methylation analysis.
site_author:      Jordi Abante

on: [push]

jobs:
  build:
    name: "Build documentation."
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3
      - name: Install CpelAsm
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Install Documenter
        run: julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl